### ISSUE TITLE
No German language in the UI

### ISSUE THREAD

**Issue by Conan179** [flathub/org.DolphinEmu.dolphin-emu#157]
Good evening. I have the following problem on my steam deck. I installed Dolphin via SteamOS (Arch Linux) app. If I try to set the UI to German, the next time I start it, I get the message that it doesn't work and falls back to Eng.
![2023-08-12 15 12 01 - Kopie](https://github.com/flathub/org.DolphinEmu.dolphin-emu/assets/1906242/7ef3b79b-2d3d-4dcf-b450-442abd8409d4)

The Version is 5.0-19870 
Here is the Logfile:
38:06:028 Common/FileUtil.cpp:781 I[COMMON]: CreateSysDirectoryPath: Setting to /app/share/dolphin-emu/sys/
38:06:042 DolphinQt/Translation.cpp:155 W[COMMON]: Error reading MO file '/app/share/dolphin-emu//../locale/de/LC_MESSAGES/dolphin-emu.mo'
38:06:043 DolphinQt/Translation.cpp:304 E[COMMON]: No suitable translation file found
38:07:856 DolphinQt/Translation.cpp:155 W[COMMON]: Error reading MO file '/app/share/dolphin-emu//../locale/en_US/LC_MESSAGES/dolphin-emu.mo'
38:08:496 InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPClient.cpp:392 I[CI]: DualShockUDPClient Restart
38:08:496 InputCommon/ControllerInterface/evdev/evdev.cpp:320 N[CI]: evdev hotplug thread started
38:08:497 InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPClient.cpp:241 I[CI]: DualShockUDPClient hotplug thread started
38:08:504 InputCommon/ControllerInterface/ControllerInterface.cpp:314 N[CI]: Added device: XInput2/0/Virtual core pointer
38:08:590 InputCommon/ControllerInterface/ControllerInterface.cpp:314 N[CI]: Added device: evdev/0/Valve Software Steam Controller
38:08:591 InputCommon/ControllerInterface/ControllerInterface.cpp:314 N[CI]: Added device: evdev/0/AT Translated Set 2 keyboard
38:08:591 InputCommon/ControllerInterface/ControllerInterface.cpp:314 N[CI]: Added device: evdev/0/Microsoft X-Box 360 pad 0
38:08:630 InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPClient.cpp:487 I[CI]: DualShockUDPClient PopulateDevices
38:08:630 InputCommon/ControllerInterface/ControllerInterface.cpp:314 N[CI]: Added device: DSUClient/0/steamdeckgyro
38:08:630 InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPClient.cpp:487 I[CI]: DualShockUDPClient PopulateDevices
38:08:630 InputCommon/ControllerInterface/ControllerInterface.cpp:351 N[CI]: Removed device: DSUClient/0/steamdeckgyro
38:08:630 InputCommon/ControllerInterface/ControllerInterface.cpp:314 N[CI]: Added device: DSUClient/0/steamdeckgyro
38:08:630 InputCommon/ControllerInterface/ControllerInterface.cpp:314 N[CI]: Added device: SDL/0/Microsoft X-Box 360 pad 0
38:08:649 Core/HW/WiimoteEmu/EmuSubroutines.cpp:186 I[Wiimote]: Attaching Motion Plus (Wiimote 0 in slot 0)
38:08:649 Core/HW/WiimoteEmu/EmuSubroutines.cpp:186 I[Wiimote]: Attaching Motion Plus (Wiimote 1 in slot 1)
38:08:649 Core/HW/WiimoteEmu/EmuSubroutines.cpp:186 I[Wiimote]: Attaching Motion Plus (Wiimote 2 in slot 2)
38:08:649 Core/HW/WiimoteEmu/EmuSubroutines.cpp:186 I[Wiimote]: Attaching Motion Plus (Wiimote 3 in slot 3)

**Comment by cpba** [comment]
I remember this one, there's some weirdness with the way the steam deck
handles locales.

Somebody else already reported it back in January.

You can read about it on the original issue:

https://github.com/flathub/org.DolphinEmu.dolphin-emu/issues/144

El dj., 17 d’ag. 2023, 20:41, Conan179 ***@***.***> va
escriure:

**Comment by cpba** [comment]
I never got any response, I assume the issue was solved, feel free to reopen if it persists.

**Comment by Conan179** [comment]
>I assume the issue was solved
The problem is not solved, I uninstalled dolphin. Nobody wanted to help I was moved from one support forum to another.

**Comment by cpba** [comment]
I don't understand, why do you think nobody wants to help?

I literally replied to your issue 6 minutes after you posted it, with a link to the original issue where both the problem and the workaround are explained.

Why would I do this if I didn't want to help?
